/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AzIcon {
    'color': string;
    'height': number;
    'icon': string;
    'width': number;
  }
  interface AzSection {
    'caption': string;
    'collapsable': boolean;
    'collapse': () => Promise<void>;
    'collapsed': boolean;
    'expand': () => Promise<void>;
  }
}

declare global {


  interface HTMLAzIconElement extends Components.AzIcon, HTMLStencilElement {}
  var HTMLAzIconElement: {
    prototype: HTMLAzIconElement;
    new (): HTMLAzIconElement;
  };

  interface HTMLAzSectionElement extends Components.AzSection, HTMLStencilElement {}
  var HTMLAzSectionElement: {
    prototype: HTMLAzSectionElement;
    new (): HTMLAzSectionElement;
  };
  interface HTMLElementTagNameMap {
    'az-icon': HTMLAzIconElement;
    'az-section': HTMLAzSectionElement;
  }
}

declare namespace LocalJSX {
  interface AzIcon extends JSXBase.HTMLAttributes<HTMLAzIconElement> {
    'color'?: string;
    'height'?: number;
    'icon'?: string;
    'width'?: number;
  }
  interface AzSection extends JSXBase.HTMLAttributes<HTMLAzSectionElement> {
    'caption'?: string;
    'collapsable'?: boolean;
    'collapsed'?: boolean;
  }

  interface IntrinsicElements {
    'az-icon': AzIcon;
    'az-section': AzSection;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


